.github/installer: build kernel separately
Downloading the rest of the installer components before building the
kernel uses too much disk space and has a risk of taking too much time.

Isolate the kernel build into its own earlier step to get the full six
hours and no unnecessary things downloaded yet.

diff --git a/.github/workflows/installer.yml b/.github/workflows/installer.yml
--- a/.github/workflows/installer.yml
+++ b/.github/workflows/installer.yml
@@ -21,8 +21,34 @@ jobs:
             # save space on disk and in cache
             auto-optimise-store = true
 
+      - name: prepare kernel build
+        run: |
+          # download everything necessary for the kernel without building. this
+          # will fail since -j0 will keep any jobs from running so we force it
+          # to succeed. if it did fail a later step should retry/catch it.
+          nix build --extra-experimental-features 'nix-command flakes' .#installer-bootstrap.config.system.build.kernel -j0 -L || true
+
+          # download the kernel source (not in cache so it's a build and wasn't done above)
+          nix build --extra-experimental-features 'nix-command flakes' .#installer-bootstrap.config.system.build.kernel.src -j1 -L -o kernel-src
+
+          # build the kernel config file here especially as it's spammy
+          nix build --extra-experimental-features 'nix-command flakes' .#installer-bootstrap.config.system.build.kernel.configfile -j1 -L
+
+      - name: build kernel
+        run: |
+          # actually build the kernel, takes ~2h and a lot of disk space
+          nix build --extra-experimental-features 'nix-command flakes' .#installer-bootstrap.config.system.build.kernel -j1 -L -o kernel
+
+      - name: clean up kernel build
+        run: |
+          # delete kernel source, saves 1-2GB
+          KERNEL_SRC=$(readlink -f kernel-src)
+          rm kernel-src
+          nix-store --delete $KERNEL_SRC
+
       - name: build installer
         run: |
+          # rest of the installer is downloaded and agglomerated and a few minor things are built
           nix build --extra-experimental-features 'nix-command flakes' .#installer-bootstrap -j2 -L
           cp result/iso/*.iso $(basename result/iso/*.iso | sed s/aarch64-linux/apple-silicon-${{ github.ref_name }}/)
 
